version: "1.0"
services:
 frontend:
    container_name: "frontend"
    #build: ./src
    image: "pictura/frontend"
    ports: 
    - "3000:80"
    tty: true
    stdin_open: true
    restart: on-failure
